import mongoose from "mongoose";

const exportTemplateSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, default: "" },
    type: {
      type: String,
      enum: ["formal", "casual", "executive", "custom"],
      default: "custom",
    },
    templateContent: { type: String, required: true },
    styles: { type: String, default: "" },
    branding: {
      logoUrl: { type: String, default: "" },
      primaryColor: { type: String, default: "#3498db" },
      headerText: { type: String, default: "Meeting Minutes" },
      footerText: { type: String, default: "Generated by MeetOnMemory" },
    },
    sections: {
      showAttendees: { type: Boolean, default: true },
      showTranscript: { type: Boolean, default: false },
      showActionItems: { type: Boolean, default: true },
      showDecisions: { type: Boolean, default: true },
      showSummary: { type: Boolean, default: true },
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    organization: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      default: null,
    },
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      default: null,
    },
    teamId: { type: mongoose.Schema.Types.ObjectId, ref: "Team" },
    isPublic: { type: Boolean, default: false },
    usageCount: { type: Number, default: 0 },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  },
);

exportTemplateSchema.index({ organization: 1, createdBy: 1 });
exportTemplateSchema.index({ organizationId: 1, createdBy: 1 });

const ExportTemplate =
  mongoose.models.ExportTemplate ||
  mongoose.model("ExportTemplate", exportTemplateSchema);

export default ExportTemplate;
