const mongoose = require("mongoose");

/**
 * @desc Stores customizable Handlebars templates for exporting meeting minutes.
 * Supports branding, section toggles, and multiple output formats.
 */
const exportTemplateSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      default: "",
    },
    type: {
      type: String,
      enum: ["formal", "casual", "executive", "custom"],
      default: "custom",
    },
    // Handlebars template string for the main document body
    templateContent: {
      type: String,
      required: true,
      default: `
        <h1>{{meeting.title}}</h1>
        <p><strong>Date:</strong> {{formatDate meeting.date}}</p>
        <p><strong>Attendees:</strong> {{join meeting.attendees ", "}}</p>
        
        <h2>Summary</h2>
        <p>{{meeting.summary}}</p>
        
        {{#if showActionItems}}
        <h2>Action Items</h2>
        <ul>
          {{#each meeting.actionItems}}
          <li><strong>{{this.title}}</strong> - Assigned to {{this.assignee}} (Due: {{formatDate this.deadline}})</li>
          {{/each}}
        </ul>
        {{/if}}
      `,
    },
    // CSS styles to inject into PDF/HTML exports
    styles: {
      type: String,
      default: `
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; margin-top: 20px; }
        ul { margin-left: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
      `,
    },
    // Branding configuration
    branding: {
      logoUrl: { type: String, default: "" },
      primaryColor: { type: String, default: "#3498db" },
      headerText: { type: String, default: "Meeting Minutes" },
      footerText: { type: String, default: "Generated by MeetOnMemory" },
    },
    // Section toggles (what to include/exclude)
    sections: {
      showAttendees: { type: Boolean, default: true },
      showTranscript: { type: Boolean, default: false },
      showActionItems: { type: Boolean, default: true },
      showDecisions: { type: Boolean, default: true },
      showSummary: { type: Boolean, default: true },
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    teamId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Team",
    },
    isPublic: {
      type: Boolean,
      default: false, // If true, available to all teams in the org
    },
    usageCount: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  },
);

module.exports = mongoose.model("ExportTemplate", exportTemplateSchema);
