const Handlebars = require("handlebars");
const PDFDocument = require("pdfkit");
const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
} = require("docx");
const fs = require("fs");

/**
 * @desc Generates PDF, DOCX, and HTML documents from structured meeting data
 * using Handlebars templates. Handles custom helpers, styling, and pagination.
 */
class DocumentGenerator {
  constructor() {
    this.registerHelpers();
  }

  /**
   * Registers custom Handlebars helpers for date formatting, grouping, etc.
   */
  registerHelpers() {
    Handlebars.registerHelper("formatDate", (date) => {
      if (!date) return "N/A";
      return new Date(date).toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    });

    Handlebars.registerHelper("join", (arr, separator) => {
      if (!Array.isArray(arr)) return "";
      return arr.map((item) => item.name || item).join(separator);
    });

    Handlebars.registerHelper("eq", (a, b) => a === b);

    Handlebars.registerHelper("truncate", (str, len) => {
      if (!str) return "";
      return str.length > len ? str.substring(0, len) + "..." : str;
    });
  }

  /**
   * Compiles the Handlebars template with the provided data.
   * @param {string} templateContent - The Handlebars template string.
   * @param {Object} data - The structured meeting data.
   * @returns {string} Rendered HTML string.
   */
  renderHTML(templateContent, data) {
    const template = Handlebars.compile(templateContent);
    return template(data);
  }

  /**
   * Generates a PDF document using PDFKit.
   * @param {string} htmlContent - Rendered HTML content.
   * @param {Object} branding - Branding config (logo, colors).
   * @returns {Promise<Buffer>} PDF buffer.
   */
  async generatePDF(htmlContent, branding) {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      // Add Logo if provided
      if (branding.logoUrl && fs.existsSync(branding.logoUrl)) {
        doc.image(branding.logoUrl, 50, 50, { width: 100 });
        doc.moveDown(4);
      }

      // Add Header
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .fillColor(branding.primaryColor || "#333");
      doc.text(branding.headerText || "Meeting Minutes", { align: "center" });
      doc.moveDown(2);

      // Parse and add content (Simplified: PDFKit doesn't natively parse HTML)
      // In production, use html-to-pdfmake or Puppeteer for complex HTML
      doc.fontSize(12).font("Helvetica").fillColor("#333");

      // Strip HTML tags for basic text rendering
      const textContent = htmlContent
        .replace(/<[^>]+>/g, " ")
        .replace(/\s+/g, " ");
      doc.text(textContent, { align: "left", lineGap: 4 });

      // Add Footer
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor("#999");
        doc.text(
          `${branding.footerText || "Generated by MeetOnMemory"} | Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 50,
          { align: "center" },
        );
      }

      doc.end();
    });
  }

  /**
   * Generates a DOCX document using the docx library.
   * @param {Object} data - Structured meeting data.
   * @param {Object} branding - Branding config.
   * @returns {Promise<Buffer>} DOCX buffer.
   */
  async generateDOCX(data, branding) {
    const children = [];

    // Title
    children.push(
      new Paragraph({
        text: data.meeting.title,
        heading: HeadingLevel.TITLE,
        alignment: "center",
        spacing: { after: 400 },
      }),
    );

    // Date and Attendees
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: "Date: ", bold: true }),
          new TextRun({
            text: new Date(data.meeting.date).toLocaleDateString(),
          }),
        ],
        spacing: { after: 200 },
      }),
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: "Attendees: ", bold: true }),
          new TextRun({
            text: data.meeting.attendees.map((a) => a.name).join(", "),
          }),
        ],
        spacing: { after: 400 },
      }),
    );

    // Summary
    if (data.meeting.summary) {
      children.push(
        new Paragraph({
          text: "Summary",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
      );
      children.push(
        new Paragraph({
          text: data.meeting.summary,
          spacing: { after: 400 },
        }),
      );
    }

    // Action Items
    if (data.meeting.actionItems && data.meeting.actionItems.length > 0) {
      children.push(
        new Paragraph({
          text: "Action Items",
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        }),
      );

      const rows = [
        new TableRow({
          children: ["Task", "Assignee", "Deadline", "Priority"].map(
            (text) =>
              new TableCell({
                children: [new Paragraph({ text, bold: true })],
              }),
          ),
        }),
      ];

      data.meeting.actionItems.forEach((item) => {
        rows.push(
          new TableRow({
            children: [
              new TableCell({ children: [new Paragraph(item.title)] }),
              new TableCell({ children: [new Paragraph(item.assignee)] }),
              new TableCell({
                children: [
                  new Paragraph(
                    item.deadline
                      ? new Date(item.deadline).toLocaleDateString()
                      : "N/A",
                  ),
                ],
              }),
              new TableCell({ children: [new Paragraph(item.priority)] }),
            ],
          }),
        );
      });

      children.push(new Table({ rows }));
    }

    const doc = new Document({
      sections: [{ children }],
      creator: branding.footerText || "MeetOnMemory",
      title: data.meeting.title,
    });

    return await Packer.toBuffer(doc);
  }
}

module.exports = new DocumentGenerator();
