import { Octokit } from "@octokit/rest";
import GithubIntegration from "../models/githubIntegrationModel.js";

/**
 * Push a new Action Item to GitHub Issues
 */
export const syncActionItemToGitHub = async (actionItem) => {
  try {
    let orgId = actionItem.organization;

    if (!orgId) {
      // If organization is not directly on the actionItem, fetch from the associated meeting
      const Meeting = (await import("../models/Meeting.js")).default;
      const meetingId = actionItem.sourceMeetingId || actionItem.meetingId;
      if (!meetingId) return;

      const meeting = await Meeting.findById(meetingId);
      if (!meeting || !meeting.organizationId) return;
      orgId = meeting.organizationId;
    }

    if (!orgId) return;

    const integration = await GithubIntegration.findOne({
      organization: orgId,
    });

    if (!integration) {
      return; // No integration found, do nothing
    }

    // 2. Setup Octokit
    const octokit = new Octokit({
      auth: integration.accessToken,
    });

    const [owner, repo] = integration.repositoryFullName.split("/");

    // 3. Create the issue payload
    const title =
      actionItem.text.length > 80
        ? actionItem.text.substring(0, 77) + "..."
        : actionItem.text;

    // Create a link back to the meeting
    const frontendUrl = process.env.CLIENT_URL || "http://localhost:3000";
    const meetingLink = `${frontendUrl}/meeting/${actionItem.sourceMeetingId}`;

    let body = `**Action Item generated by MeetOnMemory**\n\n`;
    body += `**Description:** ${actionItem.text}\n\n`;
    body += `**Source Meeting:** [View Meeting](${meetingLink})\n\n`;

    // Attempt assignment logic if needed.
    // In a production system we'd map emails to github usernames.
    // For now we just add it to the body.
    if (actionItem.owner && actionItem.owner !== "Unassigned") {
      body += `**Assigned to:** ${actionItem.owner}\n`;
    }

    // 4. Create Issue
    const response = await octokit.rest.issues.create({
      owner,
      repo,
      title,
      body,
    });

    // 5. Update ActionItem with GitHub data
    actionItem.externalGitHubIssueId = response.data.number;
    actionItem.externalGitHubIssueUrl = response.data.html_url;
    await actionItem.save();

    return response.data;
  } catch (error) {
    console.error("Error syncing Action Item to GitHub:", error);
    throw error; // Or handle silently depending on requirement
  }
};
