import axios from "axios";
import IssueTrackerIntegration from "../models/issueTrackerIntegrationModel.js";

/**
 * Push a new Action Item to Linear
 */
export const syncActionItemToLinear = async (actionItem) => {
  try {
    let orgId = actionItem.organization;

    if (!orgId) {
      const Meeting = (await import("../models/meetingModel.js")).default;
      const meetingId = actionItem.sourceMeetingId || actionItem.meetingId;
      if (!meetingId) return;

      const meeting = await Meeting.findById(meetingId);
      if (!meeting || !meeting.organizationId) return;
      orgId = meeting.organizationId;
    }

    if (!orgId) return;

    const integration = await IssueTrackerIntegration.findOne({
      organization: orgId,
      provider: "linear",
    });

    if (!integration) {
      return;
    }

    const { accessToken, config } = integration;
    if (!config || !config.teamId) {
      return;
    }

    const title =
      actionItem.text.length > 80
        ? actionItem.text.substring(0, 77) + "..."
        : actionItem.text;

    const frontendUrl = process.env.CLIENT_URL || "http://localhost:3000";
    const meetingLink = `${frontendUrl}/meeting/${actionItem.sourceMeetingId}`;

    let description = `**Action Item generated by MeetOnMemory**\n\n`;
    description += `**Description:** ${actionItem.text}\n\n`;
    description += `**Source Meeting:** [View Meeting](${meetingLink})\n\n`;

    if (actionItem.owner && actionItem.owner !== "Unassigned") {
      description += `**Assigned to:** ${actionItem.owner}\n`;
    }

    const query = `
      mutation IssueCreate($input: IssueCreateInput!) {
        issueCreate(input: $input) {
          success
          issue {
            id
            identifier
            url
          }
        }
      }
    `;

    const variables = {
      input: {
        teamId: config.teamId,
        title,
        description,
      },
    };

    const response = await axios.post(
      "https://api.linear.app/graphql",
      { query, variables },
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
      },
    );

    const issueData = response.data?.data?.issueCreate?.issue;
    if (issueData) {
      actionItem.externalLinearIssueId = issueData.id;
      actionItem.externalLinearIssueUrl = issueData.url;
      await actionItem.save();
    }

    return issueData;
  } catch (error) {
    console.error(
      "Error syncing Action Item to Linear:",
      error?.response?.data || error,
    );
    throw error;
  }
};
