import React, { useState } from "react";
import api from "../../services/api";

/**
 * @desc WYSIWYG-style editor for creating and customizing Handlebars export templates.
 * Includes a live preview pane and section configuration.
 */
const TemplateEditor = ({ template, onClose, onSave }) => {
  const [formData, setFormData] = useState(
    template || {
      name: "",
      description: "",
      type: "custom",
      templateContent: "<h1>{{meeting.title}}</h1>\n<p>{{meeting.summary}}</p>",
      styles: "body { font-family: sans-serif; }",
      branding: {
        primaryColor: "#3498db",
        headerText: "Meeting Minutes",
        footerText: "Generated by MeetOnMemory",
      },
      sections: {
        showAttendees: true,
        showActionItems: true,
        showSummary: true,
        showTranscript: false,
        showDecisions: true,
      },
    },
  );

  const [previewHtml, setPreviewHtml] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // Sample data for preview
  const sampleData = {
    meeting: {
      title: "Q3 Planning Session",
      date: new Date().toISOString(),
      summary:
        "Discussed roadmap priorities and allocated resources for the upcoming quarter.",
      attendees: [{ name: "Alice Smith" }, { name: "Bob Jones" }],
      actionItems: [
        {
          title: "Finalize budget",
          assignee: "Alice",
          deadline: new Date().toISOString(),
          priority: "high",
        },
      ],
    },
  };

  const handlePreview = async () => {
    try {
      const { data } = await api.post(`/export/templates/preview`, {
        templateContent: formData.templateContent,
        meetingData: sampleData,
      });
      setPreviewHtml(data.data.html);
    } catch (err) {
      console.error("Preview failed:", err);
    }
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      if (template?._id) {
        await api.put(`/export/templates/${template._id}`, formData);
      } else {
        await api.post("/export/templates", formData);
      }
      onSave();
      onClose();
    } catch (err) {
      console.error("Save failed:", err);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-6xl h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between bg-gray-50 dark:bg-gray-900/50">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">
            {template ? "Edit Template" : "Create New Template"}
          </h2>
          <div className="flex gap-2">
            <button
              onClick={handlePreview}
              className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 text-sm font-medium"
            >
              Preview
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 text-sm font-bold"
            >
              {isSaving ? "Saving..." : "Save Template"}
            </button>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 px-2"
            >
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>

        {/* Editor Body */}
        <div className="flex-1 flex overflow-hidden">
          {/* Left Panel: Code Editor */}
          <div className="w-1/2 border-r border-gray-200 dark:border-gray-700 flex flex-col overflow-hidden">
            <div className="p-4 border-b border-gray-200 dark:border-gray-700 space-y-3 overflow-y-auto">
              <input
                type="text"
                placeholder="Template Name"
                value={formData.name}
                onChange={(e) =>
                  setFormData({ ...formData, name: e.target.value })
                }
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white font-bold"
              />

              <textarea
                placeholder="Handlebars Template (HTML)"
                value={formData.templateContent}
                onChange={(e) =>
                  setFormData({ ...formData, templateContent: e.target.value })
                }
                rows={15}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white font-mono text-sm resize-none"
              />

              <textarea
                placeholder="CSS Styles"
                value={formData.styles}
                onChange={(e) =>
                  setFormData({ ...formData, styles: e.target.value })
                }
                rows={8}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white font-mono text-sm resize-none"
              />
            </div>
          </div>

          {/* Right Panel: Live Preview */}
          <div className="w-1/2 flex flex-col overflow-hidden bg-gray-100 dark:bg-gray-900">
            <div className="p-2 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Live Preview
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              <div className="bg-white shadow-lg rounded-lg p-8 min-h-full">
                {previewHtml ? (
                  <div dangerouslySetInnerHTML={{ __html: previewHtml }} />
                ) : (
                  <div className="text-center text-gray-400 dark:text-gray-600 py-20">
                    Click "Preview" to render template
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TemplateEditor;
